services:
  php:
    build:
      context: ./deploy
    volumes:
      - ./back-ups/app:/var/www/html
  web:
    image: nginx:1.27.0
    working_dir: /var/www/html
    volumes:
      - ./back-ups/nginx:/var/www/html
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
